Adding essential commands to build client & server images

diff --git a/client/Dockerfile b/client/Dockerfile
--- a/client/Dockerfile
+++ b/client/Dockerfile
@@ -1,5 +1,5 @@
 # Use an official node runtime as a parent image
-FROM node:14
+FROM node:14-alpine
 
 # Set the working directory in the container
 WORKDIR /app
@@ -14,16 +14,19 @@ RUN npm install
 RUN npm cache clean --force
 
 # Copy the rest of the application code
-COPY ./build .
+COPY . .
 
-# # Build the app for production
-# RUN npm run build
+# Copy the .env file
+COPY .env .env
+
+# Build the app for production and print logs if it fails
+RUN npm run build || { echo "Build failed"; exit 1; }
 
 # Install serve to serve the build
 RUN npm install -g serve
 
-# Make port 3000 available to the world outside this container
-EXPOSE 3000
+# Make port 8080 available to the world outside this container
+EXPOSE 8080
 
 # Start the app
-CMD ["serve", "-s", "build"]
+CMD ["serve", "-s", "build", "-l", "8080"]
